/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkRouteImport } from './routes/work'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as SummaryRouteImport } from './routes/summary'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as EmergencyRouteImport } from './routes/emergency'
import { Route as CommitmentsRouteImport } from './routes/commitments'
import { Route as IndexRouteImport } from './routes/index'

const WorkRoute = WorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const SummaryRoute = SummaryRouteImport.update({
  id: '/summary',
  path: '/summary',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const EmergencyRoute = EmergencyRouteImport.update({
  id: '/emergency',
  path: '/emergency',
  getParentRoute: () => rootRouteImport,
} as any)
const CommitmentsRoute = CommitmentsRouteImport.update({
  id: '/commitments',
  path: '/commitments',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/commitments': typeof CommitmentsRoute
  '/emergency': typeof EmergencyRoute
  '/settings': typeof SettingsRoute
  '/summary': typeof SummaryRoute
  '/transactions': typeof TransactionsRoute
  '/work': typeof WorkRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/commitments': typeof CommitmentsRoute
  '/emergency': typeof EmergencyRoute
  '/settings': typeof SettingsRoute
  '/summary': typeof SummaryRoute
  '/transactions': typeof TransactionsRoute
  '/work': typeof WorkRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/commitments': typeof CommitmentsRoute
  '/emergency': typeof EmergencyRoute
  '/settings': typeof SettingsRoute
  '/summary': typeof SummaryRoute
  '/transactions': typeof TransactionsRoute
  '/work': typeof WorkRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/commitments'
    | '/emergency'
    | '/settings'
    | '/summary'
    | '/transactions'
    | '/work'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/commitments'
    | '/emergency'
    | '/settings'
    | '/summary'
    | '/transactions'
    | '/work'
  id:
    | '__root__'
    | '/'
    | '/commitments'
    | '/emergency'
    | '/settings'
    | '/summary'
    | '/transactions'
    | '/work'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CommitmentsRoute: typeof CommitmentsRoute
  EmergencyRoute: typeof EmergencyRoute
  SettingsRoute: typeof SettingsRoute
  SummaryRoute: typeof SummaryRoute
  TransactionsRoute: typeof TransactionsRoute
  WorkRoute: typeof WorkRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/summary': {
      id: '/summary'
      path: '/summary'
      fullPath: '/summary'
      preLoaderRoute: typeof SummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emergency': {
      id: '/emergency'
      path: '/emergency'
      fullPath: '/emergency'
      preLoaderRoute: typeof EmergencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commitments': {
      id: '/commitments'
      path: '/commitments'
      fullPath: '/commitments'
      preLoaderRoute: typeof CommitmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CommitmentsRoute: CommitmentsRoute,
  EmergencyRoute: EmergencyRoute,
  SettingsRoute: SettingsRoute,
  SummaryRoute: SummaryRoute,
  TransactionsRoute: TransactionsRoute,
  WorkRoute: WorkRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
